on:
  schedule:
  # https://crontab.guru/
  - cron: '0 0,4,6,8,10 * * *'
name: ExWin
jobs:
  excavate:
    name: excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Excavator
      uses: shovel-org/GithubActions@main
      env:
        GITH_EMAIL: shuguang@gmail.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
